### ISSUE TITLE
Add tweet functionality?

### ISSUE THREAD

**Issue by fusillicode** [nocturnalgeek/ChuckNorrisGeekyFacts#2]
Would it be nice to add a tweet button that let you share the quote on twitter?

Btw if you agree I can try to implement it in my free time :)

**Comment by nocturnalgeek** [comment]
Hey! Yes, that would be really nice! Sure, go ahead! :)

**Comment by fusillicode** [comment]
Perfect I'll try my best to implement it as soon as I can :)

**Comment by fusillicode** [comment]
Just an update. 
I think I've implemented the basic functionality (i.e. share on twitter the Chuck's quotes). 
Now I only need to properly style the twitter button.

**Comment by nocturnalgeek** [comment]
Great! Is it complete now?

**Comment by fusillicode** [comment]
I think so :)
It remains only to properly style the "Tweet this!" button (now it has the same style of the other button) and to properly check the string trimming for the tweet ;)

**Comment by nocturnalgeek** [comment]
The style can be kept same (it will bring consistency).

**Comment by fusillicode** [comment]
As you wish then I'll proceed with the pull request as soon as I can :)

**Comment by nocturnalgeek** [comment]
Closed with #4
